### ISSUE TITLE
Workers not terminated

### ISSUE THREAD

**Issue by rosogon** [sjoerdvanderhoorn/node-red-contrib-tesseract#1]
Hi,

After running several times, I see with htop that lots of tesseract.js-overload/worker.js keep running, eating too much memory.

**Comment by oliv3** [comment]
Hi, I'm getting the same issue

```
33 /usr/local/bin/node /data/node_modules/node-red-contrib-tesseract/tesseract.js-overload/worker.js
43 /usr/local/bin/node /data/node_modules/node-red-contrib-tesseract/tesseract.js-overload/worker.js
53 /usr/local/bin/node /data/node_modules/node-red-contrib-tesseract/tesseract.js-overload/worker.js
63 /usr/local/bin/node /data/node_modules/node-red-contrib-tesseract/tesseract.js-overload/worker.js
73 /usr/local/bin/node /data/node_modules/node-red-contrib-tesseract/tesseract.js-overload/worker.js
83 /usr/local/bin/node /data/node_modules/node-red-contrib-tesseract/tesseract.js-overload/worker.js
93 /usr/local/bin/node /data/node_modules/node-red-contrib-tesseract/tesseract.js-overload/worker.js
...
```

I'm using Node-Red with docker.
I have ~= 30 processes like this, server load went to 60 and then OOM started killing processes on the host..

**Comment by oliv3** [comment]
@rosogon did https://github.com/sjoerdvanderhoorn/node-red-contrib-tesseract/pull/2 fix this ?
If yes, how can I test it ? Thanks !

**Comment by oliv3** [comment]
@sjoerdvanderhoorn @rosogon OK there is definitely a leak somewhere...
Each time I run a process there is indeed a worker.js still running...
Any idea ?

**Comment by oliv3** [comment]
@sjoerdvanderhoorn: just tested @rosogon's patch and it works fine here.
Any chance this gets merged and a new node published ? Would be so great. TIA !

**Comment by sjoerdvanderhoorn** [comment]
Thanks and apologies for not merging this any sooner; I must have missed the pull request initially.

The [updated version](https://flows.nodered.org/node/node-red-contrib-tesseract) (1.1.4) should become available pretty soon on flows.nodered.org.
